# Build and deployment pipeline for Azure DevOps
name: CI/CD Pipeline

trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main

variables:
  nodeVersion: '18.x'
  buildConfiguration: 'production'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: $(nodeVersion)
          
          - script: |
              npm ci
            displayName: 'Install dependencies'
          
          - script: |
              npm run lint
            displayName: 'Run ESLint'
          
          - script: |
              npm run build
            displayName: 'Build application'
          
          - task: PublishBuildArtifacts@1
            displayName: 'Publish build artifacts'
            inputs:
              pathToPublish: 'dist'
              artifactName: 'dist'

  - stage: Deploy
    displayName: 'Deploy Stage'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    dependsOn: Build
    jobs:
      - deployment: DeployJob
        displayName: 'Deploy Job'
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: dist
                - script: |
                    echo "Deploying to production..."
                    # Add your deployment commands here
                  displayName: 'Deploy to production'
